### PR TITLE
web: add sidebar item textures

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu,

Please review the following commits I made in branch nicks/ch10436:

4f8d1648a609690a8f524c2f9f7acc3f1d3a0cf9 (2020-12-08 18:47:33 -0500)
web: add sidebar item textures

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
cc @SurbhiSGupta 

Screenshot from 2020-12-08 18-48-04
Screenshot from 2020-12-08 18-47-54

i needed to add some new colors to the color scale, but made sure they're change-able so we can adjust them later

**Comment by nicks** [comment]
hold off, going to replace w/ the icons we talked about

**Comment by nicks** [comment]
Screenshot from 2020-12-10 11-41-24
Screenshot from 2020-12-10 11-41-08

**Comment by nicks** [comment]
updated!

**Review by hyu — APPROVED** [review]
Nice! ⚠️

**Pull request merged**
