### PR TITLE
web: logo wordmark selected state

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu,

Please review the following commits I made in branch nicks/ch10952:

0878e70748790c0829ee54a9532632cc00c23ffd (2021-01-25 17:07:12 -0500)
web: logo wordmark selected state

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
Screenshot from 2021-01-25 17-07-40
Screenshot from 2021-01-25 17-07-30

I created an svg that uses the "fillStd" class so that you can independently color the right components.

**Comment by hyu** [comment]
Visually this works, but this PR introduced an unsightly jump when navigating between Overview and Tab!




Looks like it's not present on master:

**Review by hyu — APPROVED** [review]

**Comment by nicks** [comment]
@hyu I was not able to reproduce the jump you're seeing...and I don't see anything in this PR that I would expect to change positioning. is it possible that you have a local change in your client causing this issue?

**Comment by nicks** [comment]
i think what you're seeing is a firefox flexbox bug that happens on overflow, and you have different data when you test on master. in  any case, i fixed that too while here.

**Pull request merged**
