### PR TITLE
tiltfile: remove k8s resource assembly v1

### PR DESCRIPTION
**Pull request by jazzdan**
We don't have to merge this now, just was in the code and thought that I might as well queue up the PR for when we decide to delete it.

### CODE REVIEW

**Comment by jazzdan** [comment]
@nicks should we merge this now or wait for right before v1?

**Comment by nicks** [comment]
actually, i think we should add a deprecation warning before we remove this. We still have it in some of our own demo repos, cf https://github.com/windmilleng/servantes/blob/master/Tiltfile

**Comment by jazzdan** [comment]
@nicks actually it is already deprecated https://github.com/windmilleng/tilt/blob/master/internal/tiltfile/k8s.go#L886:L886

**Comment by nicks** [comment]
@jazzdan Ya, that confused me too! But that's not the right warning. That warning shows up only if you're on version 1. It doesn't show up if you're on version 2. Since we're removing the function - _even for version 2 users_ - we need to have a deprecation warning for that

**Comment by nicks** [comment]
another option would be to just remove the implementation, but make the warning something like "this function is now a no-op, you can remove it"

**Comment by jazzdan** [comment]
Going to close this. Too many merge conflicts and we want to deprecate it first anyways.

**Pull request closed without merging**
