### PR TITLE
tiltfile: removed logging of executed command in local()

### PR DESCRIPTION
**Pull request by abdullahzameek**
Hello @nicks,

Please review the following commits I made in branch abdullahzameek/3528-remove-local-log

50e4e5b5a16f1342269d350f570319710c8a6f88  (Wed Jul 15 17:35:30 2020 +0400)
tiltfile: removed logging of executed command in local()

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by abdullahzameek** [comment]
Oops, seems like in some cases the logging of whatever in `local` is necessary, maybe the functionality of the `quiet` flag can be extended to include preventing the logging of the `local` commands?

**Comment by nicks** [comment]
can you make this an option? like `echo_off` to disable command echoing?

we think that in most cases, you need to be able to see the command tilt is echoing in case it fails

**Comment by abdullahzameek** [comment]
> can you make this an option? like `echo_off` to disable command echoing?
> 
> we think that in most cases, you need to be able to see the command tilt is echoing in case it fails

Oh right, yeah will do that then!

**Comment by abdullahzameek** [comment]
Hey @nicks !

Please find the requested changes in the following commits:
e40e4eef4ec5d5fc6a5cbe49dc7a7571339b1f7b (Wed Jul 15 18:02:45 2020 +0400) -   tiltfile: added echo_off flag to the local() function
19da162a87767a144f41bb90d486cbea843b8fd5 ( Wed Jul 15 18:06:43 2020 +0400) - added unit test for echo_off option in local()

**Comment by abdullahzameek** [comment]
Merging into master!

(The function `local()` now has an optional `echo_off` flag which, if set, prevents the logging of whatever that was inside `local()`

**Comment by abdullahzameek** [comment]
> @abdullahzameek please also make sure to update the docs repo with this new param!
Yep, I just opened a new issue for it in the repo! Will be sure to do it soon after the weekly release!

https://github.com/tilt-dev/tilt.build/issues/674

**Pull request merged**
