### PR TITLE
web: adjust the size of the all sidebar item

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu,

Please review the following commits I made in branch nicks/ch10423:

be44abd80b18e1cf7de4ff342bbf6d2b2d66ffbd (2020-12-08 16:00:00 -0500)
web: adjust the size of the all sidebar item

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
cc @SurbhiSGupta - I also made it monospace instead of sans-serif to match the mocks

Screenshot from 2020-12-08 15-59-38

**Comment by SurbhiSGupta** [comment]
@nicks monospace lgtm

**Comment by hyu** [comment]
@nicks — The height adjustment is good, but I don't see any need to change the font for "ALL" to monospace. 

@SurbhiSGupta, is it intentional to use monospace for ALL instead of the same sans font that we use for the rest of the resources? When I saw that in the mock, I assumed it was just a remnant of the old design. 

We should use the same sans font for all the resource names. To visually explain, here's a side-by-side comparison, below. I think the design on the left makes it more obvious that the "ALL" item is a selectable item, vs the design on the right where it might look a bit like a heading.

Screen Shot 2020-12-11 at 12 21 00 PM

**Review by hyu — APPROVED** [review]
Made an argument for sans vs monospace font, but it's not blocking.

**Comment by nicks** [comment]
don't worry, we have a ticket to do a design QA pass post-launch to go through a lot of these little things with Surbhi, rather than stopping to have a big discussion on them at each step of the way. I don't have a strong opinion on this either way and it's easy to change later.

**Pull request merged**
