### PR TITLE
integration: test for live_updating Dockerfile with non-root user

### PR DESCRIPTION
**Pull request by jazzdan**

### CODE REVIEW

**Comment by jazzdan** [comment]
Ah I see what's happening.

Every time we build an image now the Dockerfile is named something else. This results in a different image hash, which causes the `TestIdempotent` line to fail because the pod spec changes causing a new pod to be deployed.

Is there a way around this? Tagging in @nicks since I think you know the most about this.

**Comment by jazzdan** [comment]
ugh, this passes locally but fails remotely, hmm.

**Comment by jazzdan** [comment]
Okay, I'm at a loss @maiamcc @nicks 

This test passes for me locally, but fails in CI with: 

```
      sameimg │ Trying to build and deploy with *engine.ImageBuildAndDeployer
      sameimg │ STEP 1/5 — Building Dockerfile: [sameimg-base]
      sameimg │ Building Dockerfile:
      sameimg │   FROM busybox
      sameimg │   RUN addgroup different && adduser -D -G different different 
      sameimg │   USER different
      sameimg │   WORKDIR /src
      sameimg │   ADD . .
      sameimg │   RUN cp source.txt compiled.txt
      sameimg │ 
      sameimg │ 
      sameimg │      Tarring context…
      sameimg │      '/root/project/integration/restart_process_different_user' --> '/'
      sameimg │      Building image
      sameimg │      Step 1/7 : FROM busybox
      sameimg │       ---> c7c37e472d31
      sameimg │      Step 2/7 : RUN addgroup different && adduser -D -G different different
      sameimg │       ---> Using cache
      sameimg │       ---> cab773149087
      sameimg │      Step 3/7 : USER different
      sameimg │       ---> Using cache
      sameimg │       ---> 25cb56e5e3da
      sameimg │      Step 4/7 : WORKDIR /src
      sameimg │       ---> Using cache
      sameimg │       ---> d91b9fc7ef82
      sameimg │      Step 5/7 : ADD . .
      sameimg │       ---> Using cache
      sameimg │       ---> 9ef384cb95a1
      sameimg │      Step 6/7 : RUN cp source.txt compiled.txt
      sameimg │       ---> Running in 5fba1feb07b9
      sameimg │      cp: can't create 'compiled.txt': Permission denied
      sameimg │      
      sameimg │ ERROR: Build Failed: ImageBuild: The command '/bin/sh -c cp source.txt compiled.txt' returned a non-zero code: 1
```

I guess user `different` can't write to a directory owned by `root`? But why on earth would it pass locally?

Can either of you repro locally?

**Comment by maiamcc** [comment]
passes locally for me :-/ @nicks any ideas?

**Comment by nicks** [comment]
my shot in the dark guess is that this is a bug in an old version of docker...circleci uses docker 17 by default
https://circleci.com/docs/2.0/building-docker-images/#docker-version

lemme try upgrading it to docker 19

**Comment by nicks** [comment]
updated, try rebasing your pr on top of the new circleci config

**Comment by jazzdan** [comment]
That fixed it, thanks @nicks!

**Pull request merged**
