### PR TITLE
ospath: handle case-insensitive file systems. fixes https://github.com/tilt-dev/tilt/issues/3730

### PR DESCRIPTION
**Pull request by nicks**
Hello @maiamcc, @landism,

Please review the following commits I made in branch nicks/ch9650:

24be044572b610c04d75c30e515506468a5cff82 (2020-10-01 19:14:17 -0400)
ospath: handle case-insensitive file systems. fixes https://github.com/tilt-dev/tilt/issues/3730

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Review by landism — APPROVED** [review]
nice find, but ew :(

**Review by maiamcc — APPROVED** [review]
yuck.

**Comment by boyd-bit-io** [comment]
Thank you for fixing!

**Comment by nicks** [comment]
@boyd-bit-io thank you for sticking with it! this was a tough one to diagnose

**Pull request merged**
