### PR TITLE
server: use logger facade instead of Zap

### PR DESCRIPTION
**Pull request by milas**
This removes dependencies on `zapr` (the logr facade for Zap) and
makes logging a bit more consistent.

### CODE REVIEW

**Review by nicks — APPROVED** [review]
LGTM!

facade is a good word

**Comment by milas** [comment]
Okay, since these are obnoxiously spammy - here's a thought for an alternate approach: use [klogr](https://github.com/kubernetes/klog/tree/master/klogr) and redirect them all to `klog.v(5)` or something so they're with all the other K8s logs?

**Comment by nicks** [comment]
ya, that seems reasonable to me

**Comment by milas** [comment]
Closing in favor of #4357 which will redirect these to `klog` instead so their output can be controlled consistently along with `apiserver` & friends

**Pull request closed without merging**
