### PR TITLE
web: embiggen the trigger button and rewrite it in styled-components

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu,

Please review the following commits I made in branch nicks/ch10918:

f16aad5acf8c3c12ead55e919a9c1bbcf9251905 (2021-01-21 19:25:27 -0500)
web: embiggen the trigger button and rewrite it in styled-components
Also fixes https://github.com/tilt-dev/tilt/issues/3951

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
i ended up with something slightly different than the mocks, but i think this feels a bit more organic

Screenshot from 2021-01-21 19-14-36
Screenshot from 2021-01-21 18-58-15
Screenshot from 2021-01-21 18-57-35

**Comment by hyu** [comment]
I think this is just about ready to merge, but in Sidebar, .isSelected looks weird with the dark background behind the trigger button. Here, the icon itself should be dark on a light gray background.

Screen Shot 2021-01-21 at 8 21 01 PM

**Review by hyu — APPROVED** [review]

**Comment by nicks** [comment]
oof, good catch! I updated the storybook so that you can set all the stories to selected.

**Comment by nicks** [comment]
Screenshot from 2021-01-22 10-53-23

**Pull request merged**
