### PR TITLE
tiltfile: remove test MVP

### PR DESCRIPTION
**Pull request by nicks**
Hello @lizzthabet, @landism,

Please review the following commits I made in branch nicks/test2:

2e6d28f0d52fead9c289a3eaff1a7117148ac3a2 (2022-01-04 17:52:37 -0500)
tiltfile: remove test MVP
this is obsolete now that we have labels and
a few other minor features

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Review by landism — APPROVED** [review]

**Review by landism — COMMENTED** [review]
it looks like there are 28 repos currently using this function, which seems like enough to be worth going through a deprecation warning

**Comment by nicks** [comment]
added back!

**Comment by nicksieger** [comment]
Ha! I changed Tilt to use it too. (0b5302cb8761c7d7b52b3ac5499da71e245ce2fe) Didn't know at the time it was going away.

**Comment by nicksieger** [comment]
Nice cleanup otherwise!

**Pull request merged**
