### PR TITLE
k8s: use the Helm kube client instead of shelling out to a separate process to apply changes, try #2

### PR DESCRIPTION
**Pull request by nicks**
Hello @nicks,

Please review the following commits I made in branch nicks/ch10270:

4ea5e09504d71b0a9e13b4954a0d5695ed8dbd6a (2020-11-25 18:56:08 -0500)
k8s: use the Helm kube client instead of shelling out to a separate process to apply changes, try #2

9a9a0d2ddaf701be010c09d99f60c462145530b4 (2020-11-25 17:46:55 -0500)
Revert "k8s: use the Helm kube client instead of shelling out to a separate process to apply changes (#3945)"
This reverts commit f711652e8ad897eef857399f9ae89ebcdb8bec73.

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
just trying to run this thru ci to see what happens, will pick it up again after the holiday

**Comment by nicks** [comment]
ok! this should be like the last one, but the apply part uses the kubectl implementation

**Comment by landism** [comment]
> the apply part uses the kubectl implementation

which part is that? FWICT the only things using kubectlRunner are `Delete` and `ConnectedToCluster`

**Comment by nicks** [comment]
@landism this is the part that changed from the last PR - https://github.com/tilt-dev/tilt/pull/3956/files#diff-0155afd0b171c630accd5d9d409822f24e2c740c0863aadde28cf12315c30cc5R31

**Review by landism — APPROVED** [review]

**Pull request merged**
