### PR TITLE
docker_compose: Add auto_init param to dc_resource

### LINKED ISSUE #5176: dc_resource(auto_init=False)
`dc_resource` should have an `auto_init=False` argument, to match the argument for k8s_resource and local_resource

### PR DESCRIPTION
**Pull request by nicksieger**
Fixes #5176.

### CODE REVIEW

**Comment by nicksieger** [comment]
Are there any places where it would make sense to add a Go unit test for this?

**Comment by nicksieger** [comment]
Looks like the build failures are legit, so I may have my own answer.

**Comment by nicks** [comment]
here's a good example you can copy:
https://github.com/tilt-dev/tilt/blob/590615131d99fb3016712e2170b8893047e0110a/internal/tiltfile/tiltfile_test.go#L3522

**Review by Chimney42 — APPROVED** [review]
LGTM, but I wouldn't rely on my approval 😅

**Review by nicks — APPROVED** [review]

**Pull request merged**
