### PR TITLE
jam an apiserver into tilt

### PR DESCRIPTION
**Pull request by nicks**
Hello @ellenkorbes,

Please review the following commits I made in branch nicks/ch11034:

3ac0e95592ca6c4961fd4410062ba28980a91fb9 (2021-02-11 10:16:38 -0500)
jam an apiserver into tilt
To test:
Run: make install
Run: tilt up -f web/storybook.tiltfile
Run: kubectl --kubeconfig=./kubeconfig get manifests

735d718cfcb15c68a61febb2f98119d3b5a074f5 (2021-02-11 10:16:38 -0500)
Autogenerated by kubernetes/code-generator
scripts/update-codegen.sh

78fb7649dd963a699beb314d156aa9d59dcfc154 (2021-02-11 10:16:38 -0500)
vendor: code generation

60a26a6475b7b7172491c93e9501225e3d61e78f (2021-02-11 10:16:38 -0500)
Autogenerated by apiserver-boot
apiserver-boot create group version resource --group core --version v1alpha1 --kind Manifest

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
@ellenkorbes I updated this doc with descriptions of what this PR does:
https://docs.google.com/document/d/1h9ZCmmBkO4EuVpNzkwdiMDaUTcs_A8Jfc4pIWct0kGY/edit#

I think it still needs some rough edges cleaned up, but I think it's ready to start playing around with.

**Comment by ellenkorbes** [comment]
on it

**Comment by nicks** [comment]
this is obsoleted by https://github.com/tilt-dev/tilt/pull/4211 but leaving it up for any examples y'all are working off of

**Comment by milas** [comment]
Rebased our hacks off the latest, closing this out

**Pull request closed without merging**
