### PR TITLE
Fix local-prefixes on linters imports

### PR DESCRIPTION
**Pull request by kensipe**
Fix local-prefixes on linters imports then resolved imports to be as expected.

I've made this configuration mistake in the past and quite familiar with it.    The order of import expectations is that each group should be alphabetized and the groups are:

1. go core deps
2. 3rd party deps
3. internal to project deps

I was going to make an entry for the contributes but didn't see a logical place to drop that information.  It is fairly well adopted in OSS go projects but may add value in the contrib MD.  With some guidance, I'm happy to add to this PR or another import expectations.

Signed-off-by: Ken Sipe <kensipe@gmail.com>

### CODE REVIEW

**Comment by lizzthabet** [comment]
thanks, @kensipe! i don't remember if you were having trouble with seeing the circleci failures on an earlier pr, so i'll post the failure here just in case:

Screen Shot 2022-02-04 at 4 39 34 PM

**Comment by kensipe** [comment]
thank you @lizzthabet !   I am able to see circleci... just haven't had a chance to investigate yet... but looking now

**Comment by kensipe** [comment]
hmm.. that is strange.  it passes locally.   Continuing investigate

**Comment by kensipe** [comment]
ah.. makes sense... it has a build tag which was missed locally.  on it!

**Pull request merged**
