### PR TITLE
web: update j/k keyboard shortcuts to match tab navigation

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu, @landism,

Please review the following commits I made in branch nicks/ch10950:

b846d99e687d82143cac3ef42846370d69812d98 (2021-01-25 12:23:51 -0500)
web: update j/k keyboard shortcuts to match tab navigation

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by hyu** [comment]
So, this did not behave as I expected. I thought using j/k would change the current tab, and not open any new tabs. So, basically, keyboard navigation works exactly the same as clicking things on the sidebar. But the behavior differs. Here's a video I made with mouse nav vs keyboard nav:

**Comment by nicks** [comment]
this is basically a dataflow problem because under some conditions, react schedules the update differently. so i had to make a pretty big change to the dataflow to fix this

**Review by hyu — APPROVED** [review]

**Comment by milas** [comment]
FYI I still see the behavior from Han's GIF. I think the issue is that the [effect hook to create a tab-if-not exists](https://github.com/tilt-dev/tilt/blob/565ab5a8b4bfab51b91a847650b444958c74d79d/web/src/TabNav.tsx#L139-L143) causes a race condition. It could probably be fixed by making sure that only happens on mount, but not sure if there are other circumstances where you could end up with a tab that's not in the list 🤔

**Comment by nicks** [comment]
fwiw, i think we might end up getting rid of the tabs anyway, since the
current design thinking is that they're redundant with pinning, see:
https://app.clubhouse.io/windmill/story/11126/finalize-the-layout-for-overview

**Pull request merged**
