### PR TITLE
cli: make 'up' and server commands choose a free port

### PR DESCRIPTION
**Pull request by nicksieger**
For those Tilt users that run multiple Tilt processes on their machines (and leave them running), this PR obviates the need to manage the `--port` on which to run. `tilt up` will find and advertise the first available free port starting with 10350.

### CODE REVIEW

**Comment by nicksieger** [comment]
Thoughts on this @nicks, @milas, @landism? Selfishly looked into what this would take because I find myself running multiple Tilts often. Don't know if there was some historical reason to not pick an open port.

**Comment by nicks** [comment]
eh, i think most tools i work with on a day-to-day basis use a static port rather than a dynamic port.

i feel like every time i've written a dev server that used a dynamic port, people ended up complaining to me all the time about it. i know it sounds nice like it'd be easier, but what happens in practice is:

1) Alice runs Tilt. It starts on port X.
2) Alice forgets she has Tilt running, and starts a second instance. It starts on port X+1
3) Alice has her browser open to port X and is SUPER confused about what's happening, spends hours debugging, etc, etc

Because it's semantically weird for the behavior of Tilt to be a silent function of how many other Tilt instances you have running.

I like the pattern i've seen on a lot of nodejs devtools recently (e.g., Storybook) to notice that the port is taken and ask you to pick another port, like so:

Screenshot from 2021-12-01 12-15-51

since that helps disambiguate between the user story of "i intended to run two instances" vs "i forgot i had an instance running"

**Comment by nicks** [comment]
(the comment above is all re: semantics of using sequential dynamic ports rather than a totally random port)

**Comment by nicksieger** [comment]
That Storybook case is an interesting pattern and might be do-able. After thinking about it, the problem of auto-choosing a port is probably more of a fringe case of a power user that is intentionally running multiple Tilts.

Also somewhere in here is the ergonomics of something like #4278 or #4288 where maybe you always only run one Tilt per machine but you have the ability to dynamically add project(s)/Tiltfiles to it.

I'll leave this for a bit and see if there is more feedback, and consider the prompt-for-open-port option.

**Comment by nicks** [comment]
re: "the ability to dynamically add project(s)/Tiltfiles" - in theory we support multiple Tiltfiles in a single tilt instance right now. you can `tilt apply` new Tiltfile objects to the Tilt server. https://api.tilt.dev/core/tiltfile-v1alpha1.html . But it's not really heavily advertized/supported in the CLI, and there are probably some rough edges if you tried to do it in practice.

**Comment by nicksieger** [comment]
Yeah, and I don't think adding multiple Tiltfiles would be very useful unless/until 1) the UI handles that situation and groups resources accordingly, 2) you could specify different k8s clusters to connect to per-Tiltfile.

**Comment by nicks** [comment]
yesssss :innocent:

**Pull request closed without merging**
