### PR TITLE
apis: add LocalCommand data structures

### PR DESCRIPTION
**Pull request by nicks**
Hello @ellenkorbes, @milas,

Please review the following commits I made in branch nicks/localcommands:

131c71a52390f399fd0be27659ecdc427fe4b8ec (2021-02-24 16:28:27 -0500)
apis: add LocalCommand data structures

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
Everything in localcommand_types.go is based off a fork i did and some experiments. A lot of it is inspired by how Kubernetes models containers

Everything in probe.go is a fork of the Kubernetes probe data structures. I was having trouble getting a codegen process to work if it depended on Kubernetes types, and realized it would be easier to fork the data structures.

Everything else is autogenerated

**Review by milas — COMMENTED** [review]
Looks good to me - will defer to @ellenkorbes for final say though

**Comment by nicks** [comment]
I also wonder if we should call these `Local`, in the kubernetes style of preferring short, single-word names for base primitives

**Comment by nicks** [comment]
tbh going to split off the part of this PR that forks probe, bc i want to think on this model more

**Review by ellenkorbes — APPROVED** [review]

**Comment by nicks** [comment]
updated this to use "Cmd" like in L's doc

**Pull request merged**
