### PR TITLE
docker: use the CLI library for creating our docker client.

### PR DESCRIPTION
**Pull request by nicks**
Hello @milas, @lizzthabet,

Please review the following commits I made in branch nicks/dockerclient2:

6b1917e34eb65c0935a3753770abd4acd2753635 (2022-04-22 12:38:47 -0400)
docker: use the CLI library for creating our docker client.
Fixes https://github.com/tilt-dev/tilt/issues/4769
Fixes https://github.com/tilt-dev/tilt/issues/4878

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
tested this manually with a DOCKER_HOST="ssh://host" running over a tailscale network and it works well!

**Comment by nicks** [comment]
oops, hold on, i messed something up

**Comment by nicks** [comment]
ok, should be good now

**Review by nicksieger — APPROVED** [review]
🙌 Amazing!

**Pull request merged**
