### PR TITLE
Add /healthz check

### PR DESCRIPTION
**Pull request by atsai1220**
- Addresses https://github.com/tilt-dev/tilt/issues/5976

### CODE REVIEW

**Comment by atsai1220** [comment]
I tried digging into the circleci tests but would appreciate some guidance on why the lint step is failing. https://app.circleci.com/pipelines/github/tilt-dev/tilt/12508/workflows/3dfc90c9-5f75-4a76-8147-1ebaf42432c7/jobs/93520/steps

Thank you!

**Comment by nicks** [comment]
i kicked the lint job. i think most of the test failures are legit:
https://app.circleci.com/pipelines/github/tilt-dev/tilt/12510/workflows/f34fe8e0-2868-44a1-bd23-4594dbdf69fc/jobs/93529

**Comment by MatanAmoyal1** [comment]
Someone plan to review and push?
It will be really useful to use the latest tilt version with k8s running via Rancher

**Comment by nicks** [comment]
going to close this, since it's stale and we could never get the tests to pass. we can re-open if anyone wants to pick it up.

**Pull request closed without merging**
