### PR TITLE
web: adjust log buffering behavior to avoid screen jiggling

### PR DESCRIPTION
**Pull request by nicks**
Hello @hyu, @lizzthabet,

Please review the following commits I made in branch nicks/shuffle:

fe4c96119035f475758668bdec96c8164db275f9 (2022-02-23 17:08:27 -0500)
web: adjust log buffering behavior to avoid screen jiggling

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
this has bothered me for a while!

**Review by lizzthabet — APPROVED** [review]
lgtm! i tested with storybook tiltfile + resource, since it has such noisy output. i do see some jiggle when navigating back to a resource with a ton of logs (which i also see in the main branch, so it's not a regression). viewing a resource with a ton of active new log output does look less jiggly.

**Comment by nicks** [comment]
hmmm -- in your screenshot, it says you're testing v0.25.0, but this PR is on top of v0.25.1. so i don't think you're testing the right branch?

**Comment by lizzthabet** [comment]
@nicks, i should be on the right branch! just to clarify -- are there any backend changes that would affect the log display? (i did compile tilt while testing the build logs pr, though i tested this first and hadn't compiled tilt since the last release.)

**Comment by nicks** [comment]
hmmm i don't know why you're seeing the old behavior then

**Pull request merged**
